services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/app/

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: meetspace
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meetspace
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@meetspace.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"

volumes:
  postgres_data: 